default: pdf

MDFILE=paper.md
BIBFILE=paper.bib
LATEXFILE=paper.tex

# some variables for the paper
REPOSITORY=https://github.com/Isurwars/Correlation/
ARCHIVE=http://dx.doi.org/10.5281/zenodo.4313127
REVIEW=https://github.com/openjournals/joss-reviews/
ARCHIVEDOI=http://dx.doi.org/10.5281/zenodo.4313127
FORMATTEDDOI=10.5281/zenodo.4313127
YEAR=2020
TITLE="Correlation: An Analyzing Tool for Liquids and for Amorphous Solids"
AUTHOR="Isaías Rodríguez"
ISSUE=X
VOLUME=x
PAGE=XXX
JOURNALNAME="Journal of Open Source Software"
PUBLISHED="?? ?? 2021"
SUBMITTED="11 Decemeber 2020"
PAPERURL=????

latex: $(MDFILE) $(BIBFILE)
	# get JOSS template
	curl https://raw.githubusercontent.com/openjournals/whedon/master/resources/latex.template
	# get JOSS logo
	curl https://raw.githubusercontent.com/openjournals/whedon/master/resources/joss-logo.png > joss-logo.png
	# use pandoc and pandoc-citeproc to create LaTeX source
	pandoc --filter pandoc-citeproc --bibliography=$(BIBFILE) -V repository="$(REPOSITORY)" -V journal_name=$(JOURNALNAME) -V paper_url="$(PAPERURL)" -V archive_doi="$(ARCHIVEDOI)" -V review_issue_url="$(REVIEW)" -V formatted_doi="$(FORMATTEDDOI)" -V logo_path="joss-logo.png" -V year="$(YEAR)" -V paper_title=$(TITLE) -V citation_author=$(AUTHOR) -V issue="$(ISSUE)" -V volume="$(VOLUME)" -V page="$(PAGE)" -V submitted=$(SUBMITTED) -V published=$(PUBLISHED) -V graphics="true" -V papersize=a4paper -V geometry:margin=1in -t latex -s $(MDFILE) -o $(LATEXFILE) --template latex.template

pdf: latex
	pdflatex paper.tex
	pdflatex paper.tex

clean:
	rm paper.bcf paper.aux paper.log paper.out paper.run.xml

clean_downloads:
	rm latex.template joss-logo.png
